# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
 check:
    name: check arana-rust project
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        rust: [stable]

    env:
      RUSTFLAGS: "-D warnings"
      
    steps:
    - uses: actions/checkout@main
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: ${{ matrix.rust }}
    - run: cargo check
    
 fmt:
    name: Rustfmt
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        rust: [stable]
        
    steps:
      - uses: actions/checkout@main
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
      - run: rustup component add rustfmt
      - run: cargo fmt --all -- --check
